ALTER TABLE alert_events DROP CONSTRAINT alert_events_severity_check;
ALTER TABLE alert_events ADD CONSTRAINT alert_events_severity_check CHECK (severity IN ('INFO','WATCH','STRONG','HIGH','CRITICAL','CRITICAL_SYSTEM'));
ALTER TABLE alert_events ADD COLUMN source_outbox_seq bigint UNIQUE REFERENCES event_outbox(seq), ADD COLUMN source_event_type text, ADD COLUMN semantic_key text UNIQUE, ADD COLUMN trader_id uuid REFERENCES traders(id), ADD COLUMN realtime_alert_eligible boolean NOT NULL DEFAULT false, ADD COLUMN provisional boolean NOT NULL DEFAULT false, ADD COLUMN chain_finality text CHECK(chain_finality IS NULL OR chain_finality IN('PENDING','CONFIRMED','ORPHANED')), ADD COLUMN event_effective_at timestamptz, ADD COLUMN classification_source text, ADD COLUMN status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','RETRACTED')), ADD COLUMN read_at timestamptz, ADD COLUMN target_reference text;
UPDATE alert_events SET event_effective_at=created_at,semantic_key='legacy:'||id::text;
ALTER TABLE alert_events ALTER COLUMN event_effective_at SET NOT NULL;
CREATE TABLE alert_engine_cursor(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),last_processed_seq bigint NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now());
-- Phase adoption starts at the current durable high watermark so old LIVE events are not
-- re-announced as fresh alerts. Events committed after this migration are processed durably.
INSERT INTO alert_engine_cursor(singleton,last_processed_seq) SELECT true,COALESCE(max(seq),0) FROM event_outbox;
CREATE TABLE alert_preferences(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,sound_enabled boolean NOT NULL DEFAULT true,voice_enabled boolean NOT NULL DEFAULT false,desktop_notifications_enabled boolean NOT NULL DEFAULT false,speak_strong boolean NOT NULL DEFAULT true,speak_high_priority boolean NOT NULL DEFAULT true,speak_wallet_close boolean NOT NULL DEFAULT true,speak_distribution boolean NOT NULL DEFAULT true,speak_system_update boolean NOT NULL DEFAULT true,smart_buy_alerts boolean NOT NULL DEFAULT true,provisional_alerts boolean NOT NULL DEFAULT true,minimum_signal_score numeric NOT NULL DEFAULT 0 CHECK(minimum_signal_score BETWEEN 0 AND 100),minimum_smart_trade_amount uint256_text,updated_at timestamptz NOT NULL DEFAULT now());
