import { useEffect, useRef, useState } from 'preact/hooks';
import { AlertDelivery, AlertLeader, type AlertItem, type AlertPreferences } from './alerts';
import { api } from './api';
import { invalidateForEvent, queryClient, useQuery } from './query';
import { RealtimeClient, type ConnectionStatus } from './realtime';
import { Link, useRoute } from './router';
import { AdminPage, AlertsPage, AuthPage, BacktestsPage, DashboardPage, ResearchPage, SystemPage, TokenPage, TokensPage, TraderPage, TradersPage, UpdatesPage } from './pages';
import { CLIENT_APP_VERSION, CLIENT_BUILD_ID, CLIENT_IDENTITY, type VersionInfo } from './version';
import { AdminContentPage, TraderAnalyticsPage, TraderContentPage, TraderScoreModes } from './content-pages';
import { AutoRefreshCountdown, type BuildIdentity, compareBuilds, FRONTEND_UPDATE_CONFIG, setMutationRefreshLevel, shouldAutoRefresh, unsavedChanges, UpgradeBroadcast, type RefreshRequirement } from './upgrade';
import { Badge } from './components';

const defaults: AlertPreferences = { sound_enabled: true, voice_enabled: false, desktop_notifications_enabled: false, speak_strong: true, speak_high_priority: true, speak_wallet_close: true, speak_distribution: true, speak_system_update: true, smart_buy_alerts: true, provisional_alerts: true, minimum_signal_score: '0', minimum_smart_trade_amount: null };
interface User { id: string; username: string; role: string; }

export function App() {
  const route = useRoute(); const [user, setUser] = useState<User | null>(); const [setup, setSetup] = useState(false); const [connection, setConnection] = useState<ConnectionStatus>('OFFLINE'); const [lastSeq, setLastSeq] = useState(0); const [server, setServer] = useState('-'); const [serverIdentity, setServerIdentity] = useState<BuildIdentity>(); const [refresh, setRefresh] = useState<RefreshRequirement>(); const [dirty, setDirty] = useState(false); const [cancelled, setCancelled] = useState(false); const [countdown, setCountdown] = useState<number>(); const [preferences, setPreferences] = useState(defaults); const [enabled, setEnabled] = useState(false); const [toasts, setToasts] = useState<AlertItem[]>([]); const [alertCount, setAlertCount] = useState(0); const delivery = useRef<AlertDelivery>(); const upgradeBroadcast = useRef<UpgradeBroadcast>();
  const version = useQuery<VersionInfo>(['version'], () => api('/system/version'), Boolean(user));
  const system = useQuery<Record<string, unknown>>(['system'], () => api('/system/health'), Boolean(user));
  useEffect(() => { Promise.all([api<{ setup_required: boolean }>('/auth/setup-status'), api<User>('/auth/me').catch(() => null)]).then(([status, current]) => { setSetup(status.setup_required); setUser(current); }); const unauth = () => setUser(null); addEventListener('pons:unauthorized', unauth); return () => removeEventListener('pons:unauthorized', unauth); }, []);
  useEffect(() => unsavedChanges.subscribe(setDirty), []);
  const inspectServer = (identity: BuildIdentity, broadcast = true) => { setServer(identity.app_version); setServerIdentity(identity); const next = compareBuilds(CLIENT_IDENTITY, identity); setRefresh(next); setMutationRefreshLevel(next.level); setCancelled(false); if (next.level !== 'NONE' && broadcast) upgradeBroadcast.current?.detected(identity); };
  useEffect(() => { if (version.data) inspectServer(version.data); }, [version.data?.frontend_build_id, version.data?.api_schema_version]);
  useEffect(() => { const channel = new UpgradeBroadcast((identity) => inspectServer(identity, false)); upgradeBroadcast.current = channel; return () => { channel.close(); upgradeBroadcast.current = undefined; }; }, []);
  useEffect(() => { if (!user) return; const leader = new AlertLeader(); leader.start(); delivery.current = new AlertDelivery(leader, preferences, (alert) => setToasts((items) => [alert, ...items.filter((item) => item.id !== alert.id)].slice(0, 4))); void api<AlertPreferences>('/alert-preferences').then((value) => { setPreferences(value); delivery.current?.setPreferences(value); }); void api<AlertItem[]>('/alerts?limit=100').then((items) => setAlertCount(items.filter((item) => !('read_at' in item) || !item.read_at).length)); return () => leader.stop(); }, [user?.id]);
  useEffect(() => { if (!user) return; const realtime = new RealtimeClient(setConnection, (event) => { setLastSeq(event.seq); invalidateForEvent(event.type, event.data); if (event.type === 'system.update_applied') void api<VersionInfo>('/system/version').then(inspectServer); if (event.type.startsWith('alert.')) { delivery.current?.consume(event); setAlertCount((count) => count + (event.type === 'alert.created' ? 1 : 0)); } }, (appVersion, build, schema) => inspectServer({ app_version: appVersion, frontend_build_id: build, api_schema_version: schema })); setLastSeq(realtime.lastSeenSeq); realtime.start(); return () => realtime.stop(); }, [user?.id]);
  useEffect(() => { if (refresh && refresh.level !== 'NONE' && enabled) delivery.current?.announceUpgrade(refresh.server.frontend_build_id); }, [refresh?.server.frontend_build_id, enabled]);
  useEffect(() => { if (!refresh || refresh.level === 'NONE' || !shouldAutoRefresh(FRONTEND_UPDATE_CONFIG.auto_refresh_read_only_pages, route.path, dirty, cancelled)) { setCountdown(undefined); return; } const timer = new AutoRefreshCountdown(FRONTEND_UPDATE_CONFIG.auto_refresh_countdown_seconds, setCountdown, () => location.reload()); timer.start(); return () => timer.cancel(); }, [refresh?.server.frontend_build_id, route.path, dirty, cancelled]);
  useEffect(() => { if (refresh?.level === 'NONE') { setMutationRefreshLevel('NONE'); setCountdown(undefined); } }, [refresh?.level]);
  useEffect(() => { const show = () => refresh && setRefresh({ ...refresh }); addEventListener('pons:refresh-required', show); return () => removeEventListener('pons:refresh-required', show); }, [refresh]);
  if (user === undefined) return <main class="boot">Loading secure application…</main>;
  if (!user) return <AuthPage setup={setup} onAuthenticated={() => void api<User>('/auth/me').then(setUser)} />;
  const savePreferences = async (next: AlertPreferences) => { unsavedChanges.set('alert-preferences', true); try { setPreferences(next); delivery.current?.setPreferences(next); await api('/alert-preferences', { method: 'PUT', body: JSON.stringify(next) }); } finally { unsavedChanges.set('alert-preferences', false); } };
  const mute = () => void savePreferences({ ...preferences, sound_enabled: false, voice_enabled: false, desktop_notifications_enabled: false });
  return <div class="app-shell"><aside class="sidebar"><Link href="/dashboard" class="brand"><span>P</span><div><strong>Pons Radar</strong><small>Research Terminal</small></div></Link><nav>{[['/dashboard', 'Dashboard'], ['/tokens', 'Tokens'], ['/smart-money', 'Smart Money'], ['/traders', 'Traders'], ['/alerts', 'Alerts'], ['/research', 'Research'], ['/system', 'System'], ['/admin', 'Admin']].map(([href, label]) => <Link href={href} class={route.path.startsWith(href) ? 'active' : ''}>{label}{label === 'Alerts' && alertCount > 0 && <b>{alertCount}</b>}</Link>)}</nav><footer><span>@{user.username}</span><button onClick={() => void api('/auth/logout', { method: 'POST' }).then(() => { queryClient.clear(); setUser(null); })}>Logout</button></footer></aside><div class="workspace"><header class="topbar"><Status label="WSS" value={connection} tone={connection.toLowerCase()} /><Status label="Indexer" value={String(system.data?.postgres ?? 'UNKNOWN')} tone={system.error ? 'offline' : 'live'} /><span>v{version.data?.app_version ?? CLIENT_APP_VERSION}</span><span class="build">build {CLIENT_BUILD_ID.slice(0, 8)} · seq {lastSeq} · server {server}</span><button onClick={() => void delivery.current?.enable().then(() => setEnabled(true))}>{enabled ? 'Alerts Enabled' : 'Enable Alerts'}</button><button class={preferences.sound_enabled ? 'on' : 'muted'} onClick={mute}>Mute All</button><span>Sound {preferences.sound_enabled ? 'ON' : 'OFF'}</span><span>Voice {preferences.voice_enabled ? 'ON' : 'OFF'}</span></header><main class="content"><RoutePage path={route.path} segments={route.segments} preferences={preferences} savePreferences={savePreferences} serverIdentity={serverIdentity} /></main></div><aside class="toasts">{toasts.map((alert) => <button class={`toast ${alert.severity.toLowerCase()}`} onClick={() => alert.target_reference && location.assign(alert.target_reference)}><strong>{alert.title}</strong><span>{alert.message}</span><small>{new Date(alert.event_effective_at).toLocaleTimeString()} {alert.provisional && '· PENDING'}</small></button>)}</aside>{refresh && refresh.level !== 'NONE' && <UpgradeModal refresh={refresh} dirty={dirty} countdown={countdown} cancel={() => setCancelled(true)} reload={() => location.reload()} discard={() => { unsavedChanges.clear(); location.reload(); }} />}</div>;
}

function RoutePage({ path, segments, preferences, savePreferences, serverIdentity }: { path: string; segments: string[]; preferences: AlertPreferences; savePreferences: (v: AlertPreferences) => Promise<void>; serverIdentity?: BuildIdentity }) {
  if (segments[0] === 'tokens' && segments[1]) return <TokenPage address={segments[1]} tab={segments[2] ?? 'overview'} />;
  if (segments[0] === 'tokens') return <TokensPage />;
  if (segments[0] === 'traders' && segments[1]) return <><TraderPage id={segments[1]} /><TraderAnalyticsPage id={segments[1]} /><TraderScoreModes id={segments[1]} /><TraderContentPage id={segments[1]} /></>;
  if (segments[0] === 'traders' || path === '/smart-money') return <TradersPage />;
  if (path === '/alerts') return <AlertsPage preferences={preferences} savePreferences={savePreferences} />;
  if (segments[0] === 'research' && segments[1] === 'backtests') return <BacktestsPage id={segments[2]} />;
  if (path === '/research') return <ResearchPage />;
  if (path === '/system') return <SystemPage serverIdentity={serverIdentity} />;
  if (path === '/admin/updates') return <UpdatesPage />;
  if (path === '/admin/content') return <AdminContentPage />;
  if (path === '/admin') return <AdminPage />;
  return <DashboardPage />;
}
function Status({ label, value, tone }: { label: string; value: string; tone: string }) { return <span class={`status ${tone}`}><i />{label} {value}</span>; }
function UpgradeModal({ refresh, dirty, countdown, cancel, reload, discard }: { refresh: RefreshRequirement; dirty: boolean; countdown?: number; cancel: () => void; reload: () => void; discard: () => void }) { return <div class="upgrade-overlay" role="dialog" aria-modal="true"><section class={`upgrade-modal ${refresh.level.toLowerCase()}`}><Badge tone={refresh.level === 'CRITICAL' ? 'risk' : 'strong'}>{refresh.level === 'CRITICAL' ? 'API SCHEMA INCOMPATIBLE' : 'REFRESH REQUIRED'}</Badge><h2>系统升级已经完成</h2><p>当前页面仍运行旧版前端，需要刷新。</p><dl><div><dt>旧版本</dt><dd>{refresh.client.app_version} / {refresh.client.frontend_build_id}</dd></div><div><dt>新版本</dt><dd>{refresh.server.app_version} / {refresh.server.frontend_build_id}</dd></div></dl>{dirty ? <><div class="state error">系统已经升级，但当前页面存在未保存修改。自动刷新已禁止。请先复制或保存必要内容；旧版管理 mutation 已被安全阻断。</div><div class="modal-actions"><button disabled title="清除未保存状态后即可刷新">保存后刷新</button><button class="danger" onClick={discard}>放弃修改并刷新</button><button onClick={cancel}>暂不刷新</button></div></> : <><p>{countdown !== undefined ? `${countdown} 秒后自动刷新` : '自动刷新已取消或当前页面不允许自动刷新。'}</p><div class="modal-actions"><button onClick={reload}>立即刷新</button>{countdown !== undefined && <button onClick={cancel}>取消自动刷新</button>}</div></>}</section></div>; }
