import { useState } from 'preact/hooks';
import { api } from './api';
import { AsyncPanel, Badge, ExternalLink, Metric } from './components';
import { useQuery } from './query';
import { useUnsavedChanges } from './upgrade';

type Obj = Record<string, unknown>;
type List<T = Obj> = { items: T[] };

export function ContentItems({ items }: { items: Obj[] }) {
  return <div class="rows">{items.map((item) => <article class="row content-item" key={String(item.id)}><div><strong>@{String(item.trader_handle ?? 'Unresolved')} · {String(item.content_type)}</strong><time>{new Date(String(item.published_at)).toLocaleString()}</time>{Boolean(item.observed_later) && <Badge tone="historical">Observed later</Badge>}</div>{item.summary && <p>{String(item.summary)}</p>}<Badge>{String(item.stance ?? 'UNKNOWN')}</Badge><ExternalLink value={item.external_reference} label="External reference" /><div>{Array.isArray(item.relations) && item.relations.map((r: Obj) => <Badge>{String(r.relation_type)}</Badge>)}</div></article>)}</div>;
}

export function TraderContentPage({ id }: { id: string }) {
  const state = useQuery<{items:Obj[];stats:Obj}>(['trader', id, 'content'], () => api(`/traders/${id}/content?limit=100`));
  return <section class="section"><header><h2>Content / Trade Behavior</h2></header><AsyncPanel state={state}>{(data) => <><div class="metric-grid"><Metric label="Content" value={data.stats.content_count} /><Metric label="Theses" value={data.stats.thesis_count} /><Metric label="Before BUY" value={data.stats.thesis_before_buy_count} /><Metric label="After BUY" value={data.stats.thesis_after_buy_count} /><Metric label="Without position" value={data.stats.content_without_position_count} /><Metric label="Aligned / Divergent" value={`${String(data.stats.aligned_count)} / ${String(data.stats.divergent_count)}`} /></div><ContentItems items={data.items} /></>}</AsyncPanel></section>;
}

export function TraderAnalyticsPage({id}:{id:string}){const state=useQuery<{current:Obj|null;stats:Obj;episodes:Obj[];score_history:Obj[];score_basis:string;use_dynamic_trader_score:boolean}>(['trader',id,'analytics'],()=>api(`/traders/${id}/analytics?limit=100`));return <section class="section"><header><h2>Pons Historical Analytics</h2></header><AsyncPanel state={state}>{(data)=><>{data.current?<div class="metric-grid"><Metric label="Pons Score" value={data.current.pons_score}/><Metric label="Confidence" value={`${String(data.current.confidence)}%`}/><Metric label="Sample Size" value={data.current.sample_size}/><Metric label="Episodes" value={data.stats.episode_count}/><Metric label="Median Entry Age" value={data.stats.median_launch_age_ms}/><Metric label="Median Buyer Rank" value={data.stats.median_buyer_rank}/></div>:<div class="state empty">Pons Score unavailable: no mature confirmed episode sample.</div>}<p><Badge>Dynamic score is research-only</Badge> Manual Tier remains authoritative for Phase 11; production integration is {data.use_dynamic_trader_score?'ON':'OFF'}.</p><h3>Score Components</h3><div class="rows">{data.current&&Object.entries(data.current.components as Obj).map(([name,value])=><article class="row"><strong>{name}</strong><span>{value==null?'Unavailable':String(value)}</span></article>)}</div><h3>Position Episodes & Market Outcome Proxies</h3><div class="rows">{data.episodes.map((e)=><article class="row"><strong>Episode #{String(e.episode_number)}</strong><span>{new Date(String(e.opened_at)).toLocaleString()} → {e.closed_at?new Date(String(e.closed_at)).toLocaleString():'OPEN'}</span><span>Buyer rank {String(e.first_buyer_rank??'—')} · Adds {String(e.add_count)} · Reduces {String(e.reduce_count)}</span><Badge tone={e.position_integrity==='OK'?'exact':'warning'}>{String(e.position_integrity)}</Badge>{Array.isArray(e.outcomes)&&e.outcomes.map((o:Obj)=><Badge tone={o.status==='AVAILABLE'?'exact':'historical'}>{Number(o.horizon_seconds)/60}m {String(o.status)} {o.price_change==null?'':`${String(o.price_change)}%`}</Badge>)}{e.excursion&&<span>Observed MFE {String((e.excursion as Obj).observed_mfe??'—')} / MAE {String((e.excursion as Obj).observed_mae??'—')}</span>}</article>)}</div><h3>Score History</h3><div class="rows">{data.score_history.map((s)=><article class="row"><time>{new Date(String(s.effective_at)).toLocaleString()}</time><strong>{String(s.score)}</strong><span>Confidence {String(s.confidence)}% · n={String(s.sample_size)}</span></article>)}</div><small>{data.score_basis}; outcomes are market-price proxies, not realized trader PnL.</small></>}</AsyncPanel></section>}

export function AdminContentPage() {
  const traders = useQuery<List>(['traders'], () => api('/traders?limit=200'));
  const tokens = useQuery<List>(['tokens', 'content-admin'], () => api('/tokens?limit=200'));
  const [trader,setTrader]=useState(''); const [token,setToken]=useState(''); const [published,setPublished]=useState(''); const [reference,setReference]=useState(''); const [summary,setSummary]=useState(''); const [stance,setStance]=useState('UNKNOWN'); const [result,setResult]=useState('');
  useUnsavedChanges('manual-content-reference',Boolean(trader||token||published||reference||summary||stance!=='UNKNOWN'));
  const submit=async(e:Event)=>{e.preventDefault();const value=await api<Obj>('/admin/content-references',{method:'POST',body:JSON.stringify({trader_id:trader,token_id:token||null,content_type:'TRADE_THESIS',published_at:new Date(published).toISOString(),external_reference:reference||null,title:null,summary:summary||null,stance,narratives:[]})});setResult(value.created?'Reference saved; relation rebuild queued.':'Duplicate reference already exists.');setTrader('');setToken('');setPublished('');setReference('');setSummary('');setStance('UNKNOWN');};
  return <div class="page"><header class="page-title"><div><h1>Add Content Reference</h1><p>Save a reference and bounded operator summary only. Do not paste third-party full text.</p></div></header><form onSubmit={(e)=>void submit(e)}><label>Trader<AsyncPanel state={traders}>{(d)=><select required value={trader} onInput={(e)=>setTrader(e.currentTarget.value)}><option value="">Select</option>{d.items.map((v)=><option value={String(v.id)}>@{String(v.handle)}</option>)}</select>}</AsyncPanel></label><label>Token (optional)<AsyncPanel state={tokens}>{(d)=><select value={token} onInput={(e)=>setToken(e.currentTarget.value)}><option value="">Unresolved</option>{d.items.map((v)=><option value={String(v.id)}>{String(v.symbol??v.address)}</option>)}</select>}</AsyncPanel></label><label>Published at<input required type="datetime-local" value={published} onInput={(e)=>setPublished(e.currentTarget.value)}/></label><label>External HTTPS reference<input type="url" value={reference} onInput={(e)=>setReference(e.currentTarget.value)}/></label><label>Operator summary<textarea maxlength={4096} value={summary} onInput={(e)=>setSummary(e.currentTarget.value)}/></label><label>Stance<select value={stance} onInput={(e)=>setStance(e.currentTarget.value)}>{['BULLISH','BEARISH','NEUTRAL','UNKNOWN'].map((v)=><option>{v}</option>)}</select></label><button>Save audited reference</button>{result&&<p>{result}</p>}</form></div>;
}

export function TraderScoreModes({id}:{id:string}){const state=useQuery<{score_history:Obj[]}>(['trader',id,'analytics','time-modes'],()=>api(`/traders/${id}/analytics?limit=200`));return <section class="section"><header><h2>Score History Time Semantics</h2></header><AsyncPanel state={state}>{(data)=><>{(['KNOWLEDGE_TIME','EVENT_TIME_RECONSTRUCTED'] as const).map((mode)=><div><h3>{mode==='KNOWLEDGE_TIME'?'System-known History (Backtest Default)':'Reconstructed Event-time History (Research Only)'}</h3><p>{mode==='KNOWLEDGE_TIME'?'Only facts already available to pons-radar at that time.':'Retrospective view of when chain behavior actually occurred; not valid for production backtests.'}</p><div class="rows">{data.score_history.filter((s)=>s.as_of_mode===mode).map((s)=><article class="row"><Badge tone={mode==='KNOWLEDGE_TIME'?'exact':'historical'}>{mode}</Badge><time>{new Date(String(s.effective_at)).toLocaleString()}</time><strong>{String(s.score)}</strong><span>Confidence {String(s.confidence)}% · n={String(s.sample_size)}</span>{mode==='KNOWLEDGE_TIME'&&<small>Known at {new Date(String(s.knowledge_available_at)).toLocaleString()}</small>}</article>)}</div></div>)}</>}</AsyncPanel></section>}
